//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManagementSystem.UI.ClientManagementServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/ClientManagementSystem.DAL.Models")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientManagementSystem.UI.ClientManagementServiceReference.AddressType[] AddressTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientManagementSystem.UI.ClientManagementServiceReference.Address[] AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientManagementSystem.UI.ClientManagementServiceReference.ContactInfo[] ContactInfosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OccupationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientManagementSystem.UI.ClientManagementServiceReference.AddressType[] AddressTypes {
            get {
                return this.AddressTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressTypesField, value) != true)) {
                    this.AddressTypesField = value;
                    this.RaisePropertyChanged("AddressTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientManagementSystem.UI.ClientManagementServiceReference.Address[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientManagementSystem.UI.ClientManagementServiceReference.ContactInfo[] ContactInfos {
            get {
                return this.ContactInfosField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactInfosField, value) != true)) {
                    this.ContactInfosField = value;
                    this.RaisePropertyChanged("ContactInfos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Occupation {
            get {
                return this.OccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.OccupationField, value) != true)) {
                    this.OccupationField = value;
                    this.RaisePropertyChanged("Occupation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressType", Namespace="http://schemas.datacontract.org/2004/07/ClientManagementSystem.DAL.Models")]
    [System.SerializableAttribute()]
    public partial class AddressType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientManagementSystem.UI.ClientManagementServiceReference.Address[] AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressTypeId {
            get {
                return this.AddressTypeIdField;
            }
            set {
                if ((this.AddressTypeIdField.Equals(value) != true)) {
                    this.AddressTypeIdField = value;
                    this.RaisePropertyChanged("AddressTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientManagementSystem.UI.ClientManagementServiceReference.Address[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/ClientManagementSystem.DAL.Models")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientManagementSystem.UI.ClientManagementServiceReference.AddressType AddressTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientManagementSystem.UI.ClientManagementServiceReference.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressDetail {
            get {
                return this.AddressDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressDetailField, value) != true)) {
                    this.AddressDetailField = value;
                    this.RaisePropertyChanged("AddressDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressId {
            get {
                return this.AddressIdField;
            }
            set {
                if ((this.AddressIdField.Equals(value) != true)) {
                    this.AddressIdField = value;
                    this.RaisePropertyChanged("AddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientManagementSystem.UI.ClientManagementServiceReference.AddressType AddressType {
            get {
                return this.AddressTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressTypeField, value) != true)) {
                    this.AddressTypeField = value;
                    this.RaisePropertyChanged("AddressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressTypeId {
            get {
                return this.AddressTypeIdField;
            }
            set {
                if ((this.AddressTypeIdField.Equals(value) != true)) {
                    this.AddressTypeIdField = value;
                    this.RaisePropertyChanged("AddressTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientManagementSystem.UI.ClientManagementServiceReference.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactInfo", Namespace="http://schemas.datacontract.org/2004/07/ClientManagementSystem.DAL.Models")]
    [System.SerializableAttribute()]
    public partial class ContactInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientManagementSystem.UI.ClientManagementServiceReference.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactInfoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientManagementSystem.UI.ClientManagementServiceReference.ContactType ContactTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactTypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientManagementSystem.UI.ClientManagementServiceReference.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactDetail {
            get {
                return this.ContactDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactDetailField, value) != true)) {
                    this.ContactDetailField = value;
                    this.RaisePropertyChanged("ContactDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactInfoId {
            get {
                return this.ContactInfoIdField;
            }
            set {
                if ((this.ContactInfoIdField.Equals(value) != true)) {
                    this.ContactInfoIdField = value;
                    this.RaisePropertyChanged("ContactInfoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientManagementSystem.UI.ClientManagementServiceReference.ContactType ContactType {
            get {
                return this.ContactTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactTypeField, value) != true)) {
                    this.ContactTypeField = value;
                    this.RaisePropertyChanged("ContactType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactTypeId {
            get {
                return this.ContactTypeIdField;
            }
            set {
                if ((this.ContactTypeIdField.Equals(value) != true)) {
                    this.ContactTypeIdField = value;
                    this.RaisePropertyChanged("ContactTypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactType", Namespace="http://schemas.datacontract.org/2004/07/ClientManagementSystem.DAL.Models")]
    [System.SerializableAttribute()]
    public partial class ContactType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientManagementSystem.UI.ClientManagementServiceReference.ContactInfo[] ContactInfosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientManagementSystem.UI.ClientManagementServiceReference.ContactInfo[] ContactInfos {
            get {
                return this.ContactInfosField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactInfosField, value) != true)) {
                    this.ContactInfosField = value;
                    this.RaisePropertyChanged("ContactInfos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactTypeId {
            get {
                return this.ContactTypeIdField;
            }
            set {
                if ((this.ContactTypeIdField.Equals(value) != true)) {
                    this.ContactTypeIdField = value;
                    this.RaisePropertyChanged("ContactTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientManagementServiceReference.IClientManagementService")]
    public interface IClientManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientManagementService/AddClient", ReplyAction="http://tempuri.org/IClientManagementService/AddClientResponse")]
        void AddClient(ClientManagementSystem.UI.ClientManagementServiceReference.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientManagementService/AddClient", ReplyAction="http://tempuri.org/IClientManagementService/AddClientResponse")]
        System.Threading.Tasks.Task AddClientAsync(ClientManagementSystem.UI.ClientManagementServiceReference.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientManagementService/GetClient", ReplyAction="http://tempuri.org/IClientManagementService/GetClientResponse")]
        ClientManagementSystem.UI.ClientManagementServiceReference.Client GetClient(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientManagementService/GetClient", ReplyAction="http://tempuri.org/IClientManagementService/GetClientResponse")]
        System.Threading.Tasks.Task<ClientManagementSystem.UI.ClientManagementServiceReference.Client> GetClientAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientManagementService/GetAllClients", ReplyAction="http://tempuri.org/IClientManagementService/GetAllClientsResponse")]
        ClientManagementSystem.UI.ClientManagementServiceReference.Client[] GetAllClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientManagementService/GetAllClients", ReplyAction="http://tempuri.org/IClientManagementService/GetAllClientsResponse")]
        System.Threading.Tasks.Task<ClientManagementSystem.UI.ClientManagementServiceReference.Client[]> GetAllClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientManagementService/UpdateClient", ReplyAction="http://tempuri.org/IClientManagementService/UpdateClientResponse")]
        void UpdateClient(ClientManagementSystem.UI.ClientManagementServiceReference.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientManagementService/UpdateClient", ReplyAction="http://tempuri.org/IClientManagementService/UpdateClientResponse")]
        System.Threading.Tasks.Task UpdateClientAsync(ClientManagementSystem.UI.ClientManagementServiceReference.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientManagementService/DeleteClient", ReplyAction="http://tempuri.org/IClientManagementService/DeleteClientResponse")]
        void DeleteClient(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientManagementService/DeleteClient", ReplyAction="http://tempuri.org/IClientManagementService/DeleteClientResponse")]
        System.Threading.Tasks.Task DeleteClientAsync(int clientId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientManagementServiceChannel : ClientManagementSystem.UI.ClientManagementServiceReference.IClientManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientManagementServiceClient : System.ServiceModel.ClientBase<ClientManagementSystem.UI.ClientManagementServiceReference.IClientManagementService>, ClientManagementSystem.UI.ClientManagementServiceReference.IClientManagementService {
        
        public ClientManagementServiceClient() {
        }
        
        public ClientManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddClient(ClientManagementSystem.UI.ClientManagementServiceReference.Client client) {
            base.Channel.AddClient(client);
        }
        
        public System.Threading.Tasks.Task AddClientAsync(ClientManagementSystem.UI.ClientManagementServiceReference.Client client) {
            return base.Channel.AddClientAsync(client);
        }
        
        public ClientManagementSystem.UI.ClientManagementServiceReference.Client GetClient(int clientId) {
            return base.Channel.GetClient(clientId);
        }
        
        public System.Threading.Tasks.Task<ClientManagementSystem.UI.ClientManagementServiceReference.Client> GetClientAsync(int clientId) {
            return base.Channel.GetClientAsync(clientId);
        }
        
        public ClientManagementSystem.UI.ClientManagementServiceReference.Client[] GetAllClients() {
            return base.Channel.GetAllClients();
        }
        
        public System.Threading.Tasks.Task<ClientManagementSystem.UI.ClientManagementServiceReference.Client[]> GetAllClientsAsync() {
            return base.Channel.GetAllClientsAsync();
        }
        
        public void UpdateClient(ClientManagementSystem.UI.ClientManagementServiceReference.Client client) {
            base.Channel.UpdateClient(client);
        }
        
        public System.Threading.Tasks.Task UpdateClientAsync(ClientManagementSystem.UI.ClientManagementServiceReference.Client client) {
            return base.Channel.UpdateClientAsync(client);
        }
        
        public void DeleteClient(int clientId) {
            base.Channel.DeleteClient(clientId);
        }
        
        public System.Threading.Tasks.Task DeleteClientAsync(int clientId) {
            return base.Channel.DeleteClientAsync(clientId);
        }
    }
}
